# Docker Compose Generator
#
# Generates docker-compose.yaml with configuration from ports.nix
# This allows running the stack directly on the host without a MicroVM.
#
# Note: Uses official images where the Nix-built ones have K8s-specific configs.
{ lib, pkgs, writeText }:

let
  ports = import ./ports.nix;

  # Lua transform script for converting logs to OTel format
  luaTransform = writeText "transform.lua" ''
    -- Transform FluentBit records to OTel log format for ClickHouse
    local severity_map = {
      debug = { text = "DEBUG", num = 5 },
      info = { text = "INFO", num = 9 },
      warn = { text = "WARN", num = 13 },
      warning = { text = "WARN", num = 13 },
      error = { text = "ERROR", num = 17 },
      fatal = { text = "FATAL", num = 21 },
    }

    function format_timestamp(ts)
      if type(ts) ~= "number" then
        return os.date("!%Y-%m-%d %H:%M:%S.000000000")
      end
      local seconds = math.floor(ts)
      local nanos = math.floor((ts - seconds) * 1e9)
      return string.format("%s.%09d", os.date("!%Y-%m-%d %H:%M:%S", seconds), nanos)
    end

    function transform_to_otel(tag, timestamp, record)
      -- Parse JSON log if present
      local level = record.level or "info"
      local ts = record.ts or timestamp
      local msg = record.msg or record.log or ""
      local caller = record.caller or ""
      local count = record.count or 0
      local random_number = record.random_number or 0
      local random_string = record.random_string or ""

      -- Get service name from tag (format: loggen, docker.loggen, etc)
      local service_name = tag:match("%.?([^%.]+)$") or "unknown"

      -- Map severity
      local sev = severity_map[level] or severity_map.info

      -- Build OTel record - Map fields as Lua tables for proper JSON serialization
      local otel = {
        Timestamp = format_timestamp(ts),
        TraceId = "",
        SpanId = "",
        TraceFlags = 0,
        SeverityText = sev.text,
        SeverityNumber = sev.num,
        ServiceName = service_name,
        Body = msg,
        ResourceSchemaUrl = "",
        ResourceAttributes = { ["service.name"] = service_name },
        ScopeSchemaUrl = "",
        ScopeName = service_name,
        ScopeVersion = "1.0.0",
        ScopeAttributes = {},
        LogAttributes = { caller = caller },
        RandomNumber = random_number,
        RandomString = random_string,
        Count = count,
      }

      return 1, timestamp, otel
    end
  '';

  # FluentBit config for docker-compose (uses docker service names)
  fluentbitConf = writeText "fluent-bit.conf" ''
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  /fluent-bit/etc/parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     ${toString ports.services.fluentbitMetrics}

    [INPUT]
        Name          forward
        Listen        0.0.0.0
        Port          24224

    [FILTER]
        Name          lua
        Match         *
        script        /fluent-bit/etc/transform.lua
        call          transform_to_otel

    [OUTPUT]
        Name          http
        Match         *
        Host          clickhouse
        Port          ${toString ports.services.clickhouseHttp}
        URI           /?query=INSERT+INTO+otel_logs+FORMAT+JSONEachRow
        Format        json_lines
        Json_date_key Timestamp
        Json_date_format epoch
  '';

  # Generate docker-compose.yaml
  composeFile = writeText "docker-compose.yaml" ''
    # Generated by Nix from nix/docker-compose.nix
    # Configuration sourced from nix/ports.nix
    #
    # Usage:
    #   nix run .#compose-up    # Start the stack
    #   nix run .#compose-down  # Stop the stack
    #   nix run .#compose-logs  # View logs

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        container_name: otel-clickhouse
        ports:
          - "${toString ports.compose.clickhouseHttp}:${toString ports.services.clickhouseHttp}"
          - "${toString ports.compose.clickhouseNative}:${toString ports.services.clickhouseNative}"
        volumes:
          - clickhouse-data:/var/lib/clickhouse
          - ${clickhouseInit}:/docker-entrypoint-initdb.d/init.sql:ro
        environment:
          - CLICKHOUSE_DB=default
          - CLICKHOUSE_USER=default
          - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
        healthcheck:
          test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
          interval: 5s
          timeout: 5s
          retries: 10
        networks:
          - otel-demo

      mongodb:
        image: mongo:7
        container_name: otel-mongodb
        ports:
          - "${toString ports.compose.mongodb}:${toString ports.services.mongodb}"
        volumes:
          - mongodb-data:/data/db
          - ${mongodbInit}:/docker-entrypoint-initdb.d/init-hyperdx.js:ro
        healthcheck:
          test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
          interval: 5s
          timeout: 5s
          retries: 10
        networks:
          - otel-demo

      fluentbit:
        image: fluent/fluent-bit:latest
        container_name: otel-fluentbit
        ports:
          - "${toString ports.services.fluentbitMetrics}:${toString ports.services.fluentbitMetrics}"
          - "24224:24224"
        volumes:
          - ${fluentbitConf}:/fluent-bit/etc/fluent-bit.conf:ro
          - ${luaTransform}:/fluent-bit/etc/transform.lua:ro
        depends_on:
          clickhouse:
            condition: service_healthy
        networks:
          - otel-demo

      loggen:
        image: loggen:latest
        container_name: otel-loggen
        environment:
          - LOGGEN_MAX_NUMBER=100
          - LOGGEN_NUM_STRINGS=10
          - LOGGEN_SLEEP_DURATION=5s
          - LOGGEN_HEALTH_PORT=${toString ports.services.loggenHealth}
        ports:
          - "${toString ports.services.loggenHealth}:${toString ports.services.loggenHealth}"
        logging:
          driver: fluentd
          options:
            fluentd-address: localhost:24224
            tag: loggen
        depends_on:
          - fluentbit
        networks:
          - otel-demo

      hyperdx:
        image: hyperdx/hyperdx:latest
        container_name: otel-hyperdx
        # Override entrypoint: source original but override IS_LOCAL_APP_MODE after it sets REQUIRED_AUTH
        entrypoint: ["/bin/sh", "-c", "cp /etc/local/entry.sh /tmp/entry.sh && sed 's/REQUIRED_AUTH/DANGEROUSLY_is_local_app_mode💀/g' /etc/local/entry.sh > /tmp/entry.sh && chmod +x /tmp/entry.sh && exec /bin/sh /tmp/entry.sh"]
        environment:
          - MONGO_URI=mongodb://mongodb:${toString ports.services.mongodb}/hyperdx
          - CLICKHOUSE_HOST=clickhouse
          - CLICKHOUSE_PORT=${toString ports.services.clickhouseHttp}
          - CLICKHOUSE_USER=default
          - CLICKHOUSE_PASSWORD=
          - IS_LOCAL_APP_MODE=DANGEROUSLY_is_local_app_mode💀
          - FRONTEND_URL=http://${ports.externalHost}:${toString ports.compose.hyperdxApp}
          - NEXT_PUBLIC_API_URL=http://${ports.externalHost}:${toString ports.compose.hyperdxApi}
          - DEFAULT_CONNECTIONS=[{"name":"Default","host":"http://clickhouse:${toString ports.services.clickhouseHttp}","username":"default","password":""}]
          # TODO: Auto-config sources causes EXPLAIN ESTIMATE syntax errors in ClickHouse 26.x
          # Configure source manually via UI: Settings > Sources > Add source for default.otel_logs
          # - 'DEFAULT_SOURCES=[{"name":"OTel Logs","kind":"log","connection":"Default","from":{"databaseName":"default","tableName":"otel_logs"},"timestampValueExpression":"TimestampTime","displayedTimestampValueExpression":"Timestamp","bodyExpression":"Body","severityTextExpression":"SeverityText","serviceNameExpression":"ServiceName","traceIdExpression":"TraceId","spanIdExpression":"SpanId"}]'
          - HYPERDX_API_PORT=${toString ports.services.hyperdxApi}
          - HYPERDX_APP_PORT=${toString ports.services.hyperdxApp}
        ports:
          - "${toString ports.compose.hyperdxApi}:${toString ports.services.hyperdxApi}"
          - "${toString ports.compose.hyperdxApp}:${toString ports.services.hyperdxApp}"
        depends_on:
          clickhouse:
            condition: service_healthy
          mongodb:
            condition: service_healthy
        networks:
          - otel-demo

    networks:
      otel-demo:
        driver: bridge

    volumes:
      clickhouse-data:
      mongodb-data:
  '';

  # MongoDB init script - minimal init, let HyperDX handle user/team creation
  # NOTE: Previous seed with string IDs caused type mismatch with HyperDX's ObjectId refs
  mongodbInit = writeText "init-hyperdx.js" ''
    // Initialize hyperdx database
    // HyperDX's IS_LOCAL_APP_MODE creates team/user with proper ObjectIds
    db = db.getSiblingDB('hyperdx');
    print('HyperDX database initialized');

    // COMMENTED OUT: Previous seed caused team ObjectId mismatch
    // Our string _id: '_local_team_' didn't match HyperDX's ObjectId references
    // const teamId = '_local_team_';
    // const userId = '_local_user_';
    // db.teams.insertOne({ _id: teamId, name: 'Local Team', ... });
    // db.users.insertOne({ _id: userId, name: 'Local User', team: teamId, ... });
  '';

  # ClickHouse init SQL
  clickhouseInit = writeText "init.sql" ''
    -- HyperDX compatible OTel logs schema
    CREATE TABLE IF NOT EXISTS default.otel_logs (
        Timestamp DateTime64(9) CODEC(Delta(8), ZSTD(1)),
        TimestampTime DateTime DEFAULT toDateTime(Timestamp),
        TraceId String CODEC(ZSTD(1)),
        SpanId String CODEC(ZSTD(1)),
        TraceFlags UInt8,
        SeverityText LowCardinality(String) CODEC(ZSTD(1)),
        SeverityNumber UInt8,
        ServiceName LowCardinality(String) CODEC(ZSTD(1)),
        Body String CODEC(ZSTD(1)),
        ResourceSchemaUrl LowCardinality(String) CODEC(ZSTD(1)),
        ResourceAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
        ScopeSchemaUrl LowCardinality(String) CODEC(ZSTD(1)),
        ScopeName String CODEC(ZSTD(1)),
        ScopeVersion LowCardinality(String) CODEC(ZSTD(1)),
        ScopeAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
        LogAttributes Map(LowCardinality(String), String) CODEC(ZSTD(1)),
        INDEX idx_trace_id TraceId TYPE bloom_filter(0.001) GRANULARITY 1,
        INDEX idx_lower_body lower(Body) TYPE tokenbf_v1(32768, 3, 0) GRANULARITY 8
    )
    ENGINE = MergeTree
    PARTITION BY toDate(TimestampTime)
    PRIMARY KEY (ServiceName, TimestampTime)
    ORDER BY (ServiceName, TimestampTime, Timestamp)
    TTL TimestampTime + INTERVAL 7 DAY
    SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
  '';

  # Script to run docker-compose up
  composeUp = pkgs.writeShellApplication {
    name = "compose-up";
    runtimeInputs = [ pkgs.docker-compose ];
    text = ''
      # Check if loggen image exists (optional, uses Nix-built version)
      if ! docker image inspect loggen:latest >/dev/null 2>&1; then
        echo "Note: loggen image not found. Run 'nix run .#load-images' first to use the Nix-built loggen."
        echo "      Or the stack will start without loggen."
      fi

      echo "Starting OTel demo stack..."
      docker compose -f ${composeFile} up -d
      echo ""
      echo "Services:"
      echo "  - ClickHouse: http://localhost:${toString ports.compose.clickhouseHttp}"
      echo "  - HyperDX:    http://localhost:${toString ports.compose.hyperdxApp}"
      echo ""
      echo "Commands:"
      echo "  nix run .#compose-logs  - View logs"
      echo "  nix run .#compose-ps    - Check status"
      echo "  nix run .#compose-down  - Stop stack"
    '';
  };

  # Script to run docker-compose down
  composeDown = pkgs.writeShellApplication {
    name = "compose-down";
    runtimeInputs = [ pkgs.docker-compose ];
    text = ''
      echo "Stopping OTel demo stack..."
      docker compose -f ${composeFile} down
    '';
  };

  # Script to view logs
  composeLogs = pkgs.writeShellApplication {
    name = "compose-logs";
    runtimeInputs = [ pkgs.docker-compose ];
    text = ''
      docker compose -f ${composeFile} logs -f "$@"
    '';
  };

  # Script to run docker-compose ps
  composePs = pkgs.writeShellApplication {
    name = "compose-ps";
    runtimeInputs = [ pkgs.docker-compose ];
    text = ''
      docker compose -f ${composeFile} ps
    '';
  };

in
{
  inherit composeFile composeUp composeDown composeLogs composePs;
}
