# nix/generators/compose.nix
#
# Docker Compose manifest generator.
# Generates docker-compose.yaml from service definitions.
#
{ pkgs, lib, writeText ? pkgs.writeText }:
let
  ports = import ../ports.nix;
  constants = import ../constants.nix { inherit pkgs; };
  services = import ../services/default.nix { inherit pkgs lib; };

  networkName = constants.network.name;

  # ─── YAML Generation Helpers ───────────────────────────────────────────────
  #

  # Convert ports to compose format
  portsToCompose = portList:
    lib.concatMapStringsSep "\n" (port:
      if port.hostPort != null
      then "- \"${toString port.hostPort}:${toString port.containerPort}\""
      else "- \"${toString port.containerPort}\"")
      portList;

  # Convert env to compose format
  envToCompose = env:
    lib.concatMapStringsSep "\n" (name:
      "- ${name}=${toString env.${name}}")
      (lib.attrNames env);

  # Convert health check to compose format
  healthCheckToCompose = hc:
    if hc.type == "exec" then ''
      test: ${builtins.toJSON hc.command}
      interval: ${toString hc.interval}s
      timeout: ${toString hc.timeout}s
      retries: ${toString hc.retries}''
    else if hc.type == "http" then ''
      test: ["CMD", "curl", "-sf", "http://localhost:${if lib.isInt hc.port then toString hc.port else hc.port}${hc.path}"]
      interval: ${toString hc.interval}s
      timeout: ${toString hc.timeout}s
      retries: ${toString hc.retries}''
    else "";

  # Convert depends_on to compose format
  dependsOnToCompose = deps:
    lib.concatMapStringsSep "\n" (dep:
      "${dep}:\n    condition: service_healthy")
      deps;

  # ─── Service to Compose YAML ───────────────────────────────────────────────
  #

  serviceToCompose = service:
    let
      portsYaml = if service.ports != [] then ''
        ports:
          ${portsToCompose service.ports}'' else "";
      envYaml = if service.env != {} then ''
        environment:
          ${envToCompose service.env}'' else "";
      healthYaml = if service.healthCheck != null then ''
        healthcheck:
          ${healthCheckToCompose service.healthCheck}'' else "";
      dependsYaml = if service.dependsOn != [] then ''
        depends_on:
          ${dependsOnToCompose service.dependsOn}'' else "";
      commandYaml = if service.command != null then ''
        command: ${builtins.toJSON service.command}'' else "";
      argsYaml = if service.args != null then ''
        args: ${builtins.toJSON service.args}'' else "";
    in
    ''
      ${service.name}:
        image: ${service.image}
        container_name: ${service.containerName}
        ${commandYaml}
        ${portsYaml}
        ${envYaml}
        ${healthYaml}
        ${dependsYaml}
        networks:
          - ${networkName}
    '';

  # ─── Generate Full Compose File ────────────────────────────────────────────
  #

  # Generate services section
  servicesYaml = lib.concatMapStringsSep "\n" serviceToCompose services.ordered;

  # Full compose file
  composeContent = ''
    # Generated by Nix from nix/generators/compose.nix
    # Configuration sourced from nix/services/default.nix
    #
    # Usage:
    #   nix run .#compose-up    # Start the stack
    #   nix run .#compose-down  # Stop the stack
    #   nix run .#compose-logs  # View logs

    services:
      ${servicesYaml}

    networks:
      ${networkName}:
        driver: ${constants.network.driver}

    volumes:
      clickhouse-data:
      mongodb-data:
      redpanda-data:
  '';

in
{
  # Export the compose file content
  composeContent = composeContent;

  # Export as a file
  composeFile = writeText "docker-compose.yaml" composeContent;

  # Export individual service generators
  inherit serviceToCompose;

  # Re-export services
  inherit services;
}
